### ISSUE TITLE
Not reading 3 classes with real data?

### ISSUE THREAD

**Issue by TheFilS** [jsyoo61/nEMGNet_DiVote#1]
Hello! Your paper is really interesting and I'm trying to use this on my own EMG data - I have 3 states just like you present (M, N, and NL). I use the preprocess tool ok and I have three folders (N, M, NL) created in "data/processed" with thousands of files:

**[__main__][INFO] - N     6400
NL    5348
M     3920
Name: label, dtype: int64
D    8700
P    6968
Name: muscle_type, dtype: int64**

The problem is, when I run "python train1.py" I get an error as it seems that it does not find all three classes Notice that the tensor size is 2. So I get this message:

**warnings.warn('Lazy modules are a new feature under heavy development '
'\lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
[2024-06-14 13:41:17,043][dataset][INFO] - train/val/test: 0.3506510084248149/0.1762828695430176/0.47306612203216747
[2024-06-14 13:41:17,051][hideandseek.loss][INFO] - Weighted_crossentropyloss - CrossEntropyLoss
[2024-06-14 13:41:17,051][hideandseek.loss][INFO] - y_count: tensor([1960, 3534])
[2024-06-14 13:41:17,051][hideandseek.loss][INFO] - CrossEntropy Weighted: tensor([0.6432, 0.3568])
[2024-06-14 13:41:17,064][hideandseek.trainer][INFO] - [Node: default] Validation
[2024-06-14 13:45:12,657][hideandseek.trainer][INFO] - Validation Score: {'accuracy': 0.0}
[2024-06-14 13:45:12,657][hideandseek.trainer][INFO] - [EarlyStopping] New best score: -inf -> 0.0
[2024-06-14 13:45:12,657][hideandseek.trainer][INFO] - [EarlyStopping] Saved network: network_temp\network_0.pt
[2024-06-14 13:45:14,005][hideandseek.trainer][INFO] - [EarlyStopping][patience: 0/100]
[2024-06-14 13:45:17,883][hideandseek.trainer][WARNING] - weight tensor should be defined either for all 3 classes or no classes but got weight tensor of shape: [2]
--Return--
'\lib\site-packages\hideandseek\trainer.py(317)update()->None
-> import pdb; pdb.set_trace()
(Pdb) continue
Error executing job with overrides: []
Traceback (most recent call last):
  File "~\nEMGNet_DiVote-main\train1.py", line 82, in main
    trainer.train()
  File "\lib\site-packages\hideandseek\trainer.py", line 213, in train
    self._update_epoch(T=epoch, no_val=no_val, device=device)
  File "\lib\site-packages\hideandseek\trainer.py", line 232, in _update_epoch
    self.print(f'[Node: {self.name}][iter_sum: {self.iter}][Epoch: {epoch}/{T}][Batch: {batch_i}/{len(self.loader)}][Loss: {loss:.7f} (Avg: {self.train_meter.avg:.7f})]')
TypeError: unsupported format string passed to NoneType.__format__

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.**

Do you know why the tensor is being incorrectly sized in train1.py ? Are there any other settings I need to adjust that may be affecting this? I can't seem to find anything. In the config for nEMGNet I can only fund the number of classes I have (which should be 3), but it isn't being found in the data.

Happy to share more info if needed
Thank you!

**Comment by TheFilS** [comment]
SOLVED: File names matter

If anyone ends up having the same issue as me, a fix is to change your file names. I had some file names with an "N" in front, in which case it classified all my data of a certain class as belonging to one patient. So it didn't have enough data points. I renamed my file and it worked.
